import { randomUUID } from "crypto";
import type { AgentEvent } from "./events";
import { isBuildRequest } from "./events";
import { runTool } from "./tools";

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

function step(
  label: string,
  kind: "plan" | "tool" | "validate" | "fix" | "done" | "error",
  status: "running" | "done" | "error",
  detail?: string,
  id = randomUUID(),
): AgentEvent {
  return { type: "trace", step: { id, label, kind, status, detail } };
}

async function* streamText(text: string): AsyncGenerator<AgentEvent> {
  const tokens = text.match(/\S+\s*/g) ?? [text];
  for (const t of tokens) {
    yield { type: "delta", delta: t };
    await sleep(8);
  }
}

function titleCase(s: string) {
  return s.replace(/\b\w/g, (c) => c.toUpperCase());
}

function projectName(prompt: string) {
  const cleaned = prompt
    .replace(/^(please\s+)?(build|create|make|generate|design|write)\s+(me\s+)?(a|an|the)?\s*/i, "")
    .split(/[.,\n]/)[0]
    .trim();
  return titleCase(cleaned.split(/\s+/).slice(0, 5).join(" ") || "New Project");
}

function buildFiles(prompt: string) {
  const name = projectName(prompt);
  const isTodo = /to-?do|task|checklist/i.test(prompt);
  const accent = isTodo ? "#0f766e" : "#4f46e5";

  const html = `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${name}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header class="nav">
    <a class="brand" href="#top"><span class="dot"></span>${name}</a>
    <nav>
      <a href="#features">Features</a>
      <a href="#work">${isTodo ? "Tasks" : "Showcase"}</a>
      <a class="cta" href="#work">Get started</a>
    </nav>
  </header>

  <main id="top">
    <section class="hero">
      <p class="eyebrow">Built by DeepThink</p>
      <h1>${name}</h1>
      <p class="sub">${
        isTodo
          ? "A fast, focused task list. Add it, do it, clear it — no accounts, no clutter."
          : "A clean, responsive starting point generated from a single instruction."
      }</p>
      <div class="row">
        <a class="btn" href="#work">${isTodo ? "Add your first task" : "Explore"}</a>
        <a class="btn ghost" href="#features">How it works</a>
      </div>
    </section>

    <section id="features" class="grid">
      <article class="card"><h3>Fast</h3><p>Zero dependencies, ships as plain HTML, CSS and JavaScript.</p></article>
      <article class="card"><h3>Responsive</h3><p>Mobile-first layout that holds up from 375px to widescreen.</p></article>
      <article class="card"><h3>Yours</h3><p>Every file is editable in the Code tab and exportable as a ZIP.</p></article>
    </section>

    <section id="work" class="panel">
      <h2>${isTodo ? "Your tasks" : "Interactive demo"}</h2>
      <form id="entry-form" autocomplete="off">
        <input id="entry-input" type="text" placeholder="${isTodo ? "What needs doing?" : "Type something…"}" aria-label="New item" />
        <button type="submit">Add</button>
      </form>
      <ul id="entry-list" class="list"></ul>
      <p id="empty" class="empty">Nothing here yet — add your first item.</p>
    </section>
  </main>

  <footer><p>© ${new Date().getFullYear()} ${name}. Generated by DeepThink.</p></footer>
  <script src="app.js"></script>
</body>
</html>
`;

  const css = `:root {
  --bg: #faf9f7;
  --surface: #ffffff;
  --text: #1c1917;
  --muted: #78716c;
  --accent: ${accent};
  --radius: 16px;
  --shadow: 0 1px 2px rgba(28,25,23,.06), 0 12px 32px -12px rgba(28,25,23,.14);
}
* { box-sizing: border-box; }
body {
  margin: 0; background: var(--bg); color: var(--text);
  font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", Inter, sans-serif;
  line-height: 1.65;
}
a { color: inherit; text-decoration: none; }
.nav {
  position: sticky; top: 0; z-index: 10; display: flex; align-items: center;
  justify-content: space-between; gap: 16px; padding: 16px 24px;
  background: rgba(250,249,247,.8); backdrop-filter: blur(10px);
}
.brand { display: flex; align-items: center; gap: 10px; font-weight: 650; }
.dot { width: 12px; height: 12px; border-radius: 4px; background: var(--accent); }
.nav nav { display: flex; align-items: center; gap: 20px; font-size: 14px; color: var(--muted); }
.nav .cta { background: var(--accent); color: #fff; padding: 8px 16px; border-radius: 999px; }
main { max-width: 1040px; margin: 0 auto; padding: 0 24px 80px; }
.hero { padding: 96px 0 64px; max-width: 680px; }
.eyebrow { text-transform: uppercase; letter-spacing: .12em; font-size: 12px; color: var(--accent); margin: 0 0 12px; }
h1 { font-size: clamp(36px, 6vw, 60px); line-height: 1.08; letter-spacing: -.03em; margin: 0 0 16px; }
.sub { font-size: 18px; color: var(--muted); margin: 0 0 28px; }
.row { display: flex; flex-wrap: wrap; gap: 12px; }
.btn { background: var(--accent); color: #fff; padding: 12px 22px; border-radius: 999px; font-weight: 550; }
.btn.ghost { background: transparent; color: var(--text); box-shadow: inset 0 0 0 1px rgba(28,25,23,.12); }
.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); padding: 24px 0; }
.card, .panel { background: var(--surface); border-radius: var(--radius); box-shadow: var(--shadow); padding: 24px; }
.card h3 { margin: 0 0 8px; font-size: 17px; }
.card p { margin: 0; color: var(--muted); font-size: 15px; }
.panel { margin-top: 32px; }
.panel h2 { margin: 0 0 16px; font-size: 22px; letter-spacing: -.02em; }
form { display: flex; gap: 8px; margin-bottom: 16px; }
input {
  flex: 1; padding: 12px 14px; border-radius: 12px; font: inherit;
  border: 1px solid rgba(28,25,23,.12); background: var(--bg);
}
input:focus { outline: 2px solid var(--accent); outline-offset: 1px; }
button { font: inherit; cursor: pointer; border: 0; border-radius: 12px; padding: 12px 18px; background: var(--accent); color: #fff; }
.list { list-style: none; margin: 0; padding: 0; display: grid; gap: 8px; }
.list li { display: flex; align-items: center; gap: 12px; padding: 12px 14px; border-radius: 12px; background: var(--bg); }
.list li.done span { text-decoration: line-through; color: var(--muted); }
.list li span { flex: 1; }
.list li button { background: transparent; color: var(--muted); padding: 4px 8px; }
.empty { color: var(--muted); font-size: 14px; }
footer { padding: 32px 24px; text-align: center; color: var(--muted); font-size: 14px; }
@media (max-width: 640px) { .nav nav a:not(.cta) { display: none; } .hero { padding: 64px 0 40px; } }
`;

  const js = `const form = document.getElementById("entry-form");
const input = document.getElementById("entry-input");
const list = document.getElementById("entry-list");
const empty = document.getElementById("empty");
const KEY = "deepthink.items";

let items = JSON.parse(localStorage.getItem(KEY) || "[]");

function persist() {
  localStorage.setItem(KEY, JSON.stringify(items));
}

function render() {
  list.innerHTML = "";
  empty.hidden = items.length > 0;
  items.forEach((item, i) => {
    const li = document.createElement("li");
    if (item.done) li.classList.add("done");

    const toggle = document.createElement("input");
    toggle.type = "checkbox";
    toggle.checked = item.done;
    toggle.setAttribute("aria-label", "Toggle " + item.text);
    toggle.addEventListener("change", () => {
      items[i].done = toggle.checked;
      persist();
      render();
    });

    const label = document.createElement("span");
    label.textContent = item.text;

    const remove = document.createElement("button");
    remove.type = "button";
    remove.textContent = "Remove";
    remove.addEventListener("click", () => {
      items.splice(i, 1);
      persist();
      render();
    });

    li.append(toggle, label, remove);
    list.append(li);
  });
}

form.addEventListener("submit", (event) => {
  event.preventDefault();
  const text = input.value.trim();
  if (!text) return;
  items.push({ text, done: false });
  input.value = "";
  persist();
  render();
});

render();
`;

  const readme = `# ${name}

Generated by **DeepThink** from a single instruction:

> ${prompt.trim()}

## Files
- \`index.html\` — markup and page structure
- \`styles.css\` — design system (tokens, layout, responsive rules)
- \`app.js\` — interactive list with localStorage persistence
- \`README.md\` — this file

## Run it
Open \`index.html\` in a browser, or export the project as a ZIP from the Workspace panel.
`;

  return { name, files: [
    { path: "index.html", content: html },
    { path: "styles.css", content: css },
    { path: "app.js", content: js },
    { path: "README.md", content: readme },
  ] };
}

export async function* runFallbackAgent(
  conversationId: string,
  prompt: string,
  demoNotice: string,
): AsyncGenerator<AgentEvent> {
  if (!isBuildRequest(prompt)) {
    yield* streamText(
      `${demoNotice}\n\nI can still talk things through. You asked:\n\n> ${prompt.trim()}\n\n` +
        "Here's how I'd approach it:\n\n" +
        "1. Clarify the outcome you want in one sentence.\n" +
        "2. Break it into the smallest steps that each produce something testable.\n" +
        "3. Build the thinnest end-to-end slice first, then deepen it.\n\n" +
        "Add a `DEEPSEEK_API_KEY` to your environment and I'll answer with the real model, " +
        "with full reasoning and tool use.",
    );
    return;
  }

  const { name, files } = buildFiles(prompt);

  const planId = randomUUID();
  yield step("Planning approach", "plan", "running", undefined, planId);
  await sleep(300);
  yield step("Planned 4 steps", "plan", "done", "scaffold → style → behaviour → validate", planId);

  yield* streamText(
    `${demoNotice}\n\n**Plan**\n\n1. Scaffold \`index.html\` with semantic sections for ${name}.\n` +
      "2. Write `styles.css` with design tokens and a mobile-first responsive layout.\n" +
      "3. Add `app.js` for the interactive list with localStorage persistence.\n" +
      "4. Run a build check and write the README.\n\n",
  );

  for (const file of files) {
    const id = randomUUID();
    yield step(`Creating file: ${file.path}`, "tool", "running", undefined, id);
    const res = await runTool(conversationId, "file_write", file);
    await sleep(160);
    yield step(res.label, "tool", res.ok ? "done" : "error", res.detail, id);
    if (res.terminal) yield { type: "terminal", lines: res.terminal };
    yield { type: "files" };
  }

  const vid = randomUUID();
  yield step("Running build check", "validate", "running", undefined, vid);
  const build = await runTool(conversationId, "run_command", { command: "build" });
  await sleep(250);
  yield step("Build check", "validate", build.ok ? "done" : "error", build.detail, vid);
  if (build.terminal) yield { type: "terminal", lines: build.terminal };

  yield step("Task complete", "done", "done", `${files.length} files`);

  yield* streamText(
    `**Done — ${name} is built.**\n\n` +
      files.map((f) => `- \`${f.path}\``).join("\n") +
      "\n\nOpen the **Workspace** panel on the right: *Preview* renders it live, *Code* shows every file, " +
      "*Terminal* has the build log. Use **Export ZIP** to download it.\n\n" +
      "Next steps I'd suggest:\n" +
      "1. Add a dark mode toggle driven by `prefers-color-scheme`.\n" +
      "2. Persist items to an API instead of localStorage.\n" +
      "3. Add keyboard shortcuts for add/complete.\n",
  );
}
